### ISSUE TITLE
Error on Activate

### ISSUE THREAD

**Issue by Krammig** [sjinks/wp-two-factor-auth#4]
Curious to try this plugin however I get the following error when Activating the plugin. 

`Fatal error: Uncaught Error: Class 'WildWolf\TFA\Plugin' not found in G:\RainbowWeb\test\httpdocs\wp-content\plugins\wp-two-factor-auth-master\plugin.php:23 Stack trace: #0 G:\RainbowWeb\test\httpdocs\wp-admin\includes\plugin.php(2286): include_once() #1 G:\RainbowWeb\test\httpdocs\wp-admin\plugins.php(191): plugin_sandbox_scrape('wp-two-factor-a...') #2 {main} thrown in G:\RainbowWeb\test\httpdocs\wp-content\plugins\wp-two-factor-auth-master\plugin.php on line 23`

**Comment by sjinks** [comment]
How do you install it? The correct way is with `composer`, like this:

```bash
composer require wildwolf/wp-two-factor-auth
```

**Comment by Krammig** [comment]
Thanks for the reply.

It is running under IIS on a Windows machine. I don't think composer is available on that  ?


________________________________

**Comment by sjinks** [comment]
Please try this file:

[wp-two-factor-auth.zip](https://github.com/sjinks/wp-two-factor-auth/files/7647562/wp-two-factor-auth.zip)

I am working on the automatic generation of an installable zip archive (so that you can just upload the archive into WordPress), but this might take some time.

**Comment by Krammig** [comment]
Ok thanks, will try this now.

________________________________

**Comment by Krammig** [comment]
It has installed and activated Ok this time which is great.

However now when trying to log using the OTP app I am getting this message ;

Warning: pack(): 64-bit format codes are not available for 32-bit versions of PHP in G:\RainbowWeb\test\httpdocs\wp-content\plugins\wp-two-factor-auth\vendor\wildwolf\php-otp\src\OTP.php on line 11

and

ERROR: The one time password you have entered is incorrect.

Cheers


________________________________

**Comment by sjinks** [comment]
Could you please try to amend this file: `vendor/wildwolf/php-otp/src/OTP.php`:

Find
```php
$counter = pack('J', $counter);
```

Replace with
```php
$counter = PHP_INT_SIZE === 8 ? pack('J', $counter) : pack('N*', 0, $counter);
```

If this works for you, I will release a hotfix later.
